### PR TITLE
tag repo for every handler in serverless stack

### PR DESCRIPTION
**Pull request by jdiebold**

### CODE REVIEW

**Comment by jdiebold** [comment]
tested, worked on our repo

**Comment by mgerlach** [comment]
@danepowell any chance to get this merged eventually?

**Comment by danepowell** [comment]
Sorry I no longer use Serverless in my daily work so I can't effectively review this. If you say it's ready to go, I'll trust you :)

**Comment by mgerlach** [comment]
Hi @danepowell , thank you!

Could you also add a tag please and make sure the new version can be found by using just 

    "serverless-version-tracker": "^1.1.0"  ?
    
  in package.json ?

**Comment by danepowell** [comment]
I think it's done. I haven't published many NPM packages lately so let me know if there are any problems.

**Comment by mgerlach** [comment]
Thanks, it works. Let's see if dependabot also picks it up automatically (usually that takes a while).

**Pull request merged**
